# This is a simple workflow to build this Django project and deploy it as a Google App Engine service
name: deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build project
        id: build
        run: |
          python src/manage.py collectstatic --noinput
          python src/manage.py makemigrations
          python src/manage.py migrate

      - name: Deploy application on Google App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
